### ISSUE TITLE
supporting Rails.cache.fetch_multi

### ISSUE THREAD

**Issue by rogozin** [redis-store/redis-store#235]
This code raises an exception:

```
Rails.cache.write('a', 3)
Rails.cache.write('b', 4)
Rails.cache.fetch_multi('a', 'b')
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:54:in `interpolate'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:37:in `block in mget'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:37:in `map'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:37:in `mget'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:68:in `read_multi'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/cache.rb:372:in `fetch_multi'
	from (irb):26
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/app_rails_loader.rb:45:in `require'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/app_rails_loader.rb:45:in `block in exec_app_rails'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/app_rails_loader.rb:34:in `loop'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/cli.rb:5:in `<top (required)>'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/ilya/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/railties-4.2.0/bin/rails:9:in `<top (required)>'
	from /Users/ilya/.rbenv/versions/2.1.0/bin/rails:23:in `load'
```

**Comment by radar** [comment]
Hi @rogozin,

Could you please write a PR to fix this issue? Thanks!

**Comment by dreyks** [comment]
fixed this
redis-store/redis-store#244
