### ISSUE TITLE
support for redis sentinel

### ISSUE THREAD

**Issue by runa** [redis-store/redis-store#243]
Hello,

We're setting up a redis cluster and I was wondering if there's support for this in redis-store.
[redis-rb is sentinel ready](https://github.com/redis/redis-rb#sentinel-support), so I guess it should be easy to implement.

I could work on it and send you a PR?

**Comment by radar** [comment]
Yes please, a PR would be welcome :)

**Comment by runa** [comment]
funny. I didn't had to do anything, just pass a 
```ruby
{
  sentinels: [{host: foo, port: 2679},{host: bar, port: 2679} ],
  url: "redis://mymaster/0"
}
```

and voilá.

thanks :)

**Comment by radar** [comment]
MAGIC!

**Comment by palexvs** [comment]
Strange, it does not work for me, when is master is down i get this error:

```
Redis::CannotConnectError: Error connecting to Redis on master.local:6379 (Errno::ECONNREFUSED)
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:331:in `rescue in establish_connection'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic-redis-2.0.2/lib/newrelic_redis/instrumentation.rb:36:in `block in call_with_newrelic_trace'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/datastores.rb:111:in `block in wrap'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:69:in `block in trace_execution_scoped'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:67:in `trace_execution_scoped'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/datastores.rb:108:in `wrap'
... 10 levels...
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-store-1.1.4/lib/redis/store/ttl.rb:6:in `set'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `block in set'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/activesupport-4.1.10/lib/active_support/cache.rb:548:in `instrument'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
  from (irb):1
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands/console.rb:90:in `start'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands/console.rb:9:in `start'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:69:in `console'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  from /home/rails/project/shared/bundle/ruby/2.2.0/gems/railties-4.1.10/lib/rails/commands.rb:17:in `<top (required)>'
  from ./bin/rails:8:in `require'
  from ./bin/rails:8:in `<main>'irb(main):002:0> 
```

My settings:
```ruby
/config/application.rb

o = {
  url: "redis://master.local:6379/2",
  sentinels: [
    {host: "sentinel1.local", port: 26379},
    {host: "sentinel2.local", port: 26379},
  ]
}
config.cache_store = :redis_store, o, { expires_in: 1.day }
```

Command that raise the exception:
```
Rails.cache.write('test', true, {expires_in: 1.hour.to_i})
```

If i work with redis directly everything is OK:
Sentinels are configured properly and work:
```ruby
> o = {
  url: "redis://master.local:6379/2",
  sentinels: [
    {host: "sentinel1.local", port: 26379},
    {host: "sentinel2.local", port: 26379},
  ]
}
> redis = Redis.new(o)
> redis.set('test','1')
=> OK
```

**Comment by runa** [comment]
I think you should change that redis://master.local:6379 for the name of
the master in the cluster (ie,   `url: 'redis://mymaster/0'`)

**Comment by palexvs** [comment]
The issue was in that keys were strings, not symbols:
```
o = {
  "url" => "redis://master.local:6379/2",
  "sentinels" => [
    {"host" => "sentinel1.local", "port" => 26379},
    {"host" => "sentinel2.local", "port" => 26379},
  ]
}
```

This `deep_symbolize_keys` helped me:
```
config.cache_store = :redis_store, o.deep_symbolize_keys, { expires_in: 1.day }
```

Thanks
