### ISSUE TITLE
redis-store automatically grabbing (unconfigured) cache: Error connecting to Redis on 127.0.0.1:6379

### ISSUE THREAD

**Issue by mugwump** [redis-store/redis-store#247]
I've just moved my redis from localhost to another machine: I'm setting up the session-store with: 

```
MyApp::Application.config.session_store :redis_store, :servers => { :host => ENV['REDIS_HOST'], :port => ENV['REDIS_PORT'], :namespace => 'sessions'}
```

and this works fine. However, the first time I load a translation, I'm now getting: 
```
Error connecting to Redis on 127.0.0.1:6379
```

from a ``` I18n.t "sample.translation"```.

which looks like: 

a) redis-store has grabbed the cache for the i18n
b) this cache is not properly configured. 

I'm actually using dalli/memcached for caching, so I've got no idea, why this is happening and how I can configure this store - does anyone have an idea where I can find&override this auto-magic code?!

**Comment by radar** [comment]
Can you please provide a stack trace for this error? That should shed some light on where this is happening.

**Comment by mugwump** [comment]
Sorry, didn't post it, as it was not very helpful (at least for me) - the i18n-keyvalue-store gives the exception, as it already has a mis-configured Redis-connection...

```
Error connecting to Redis on 127.0.0.1:6379 (ECONNREFUSED)
Extracted source (around line #2):
  = requirejs_include_tag "home"
  - title t'audiopitches'
  
  - content_for :page_style, 'home'

redis (3.1.0) lib/redis/client.rb:309:in `rescue in establish_connection'
redis (3.1.0) lib/redis/client.rb:304:in `establish_connection'
redis (3.1.0) lib/redis/client.rb:85:in `block in connect'
redis (3.1.0) lib/redis/client.rb:266:in `with_reconnect'
redis (3.1.0) lib/redis/client.rb:84:in `connect'
redis (3.1.0) lib/redis/client.rb:326:in `ensure_connected'
redis (3.1.0) lib/redis/client.rb:197:in `block in process'
redis (3.1.0) lib/redis/client.rb:279:in `logging'
redis (3.1.0) lib/redis/client.rb:196:in `process'
redis (3.1.0) lib/redis/client.rb:102:in `call'
redis (3.1.0) lib/redis.rb:784:in `block in get'
redis (3.1.0) lib/redis.rb:37:in `block in synchronize'
/Users/sfrank/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
redis (3.1.0) lib/redis.rb:37:in `synchronize'
redis (3.1.0) lib/redis.rb:783:in `get'
i18n (0.6.11) lib/i18n/backend/key_value.rb:92:in `lookup'
i18n (0.6.11) lib/i18n/backend/base.rb:26:in `translate'
i18n (0.6.11) lib/i18n/backend/chain.rb:46:in `block (2 levels) in translate'
i18n (0.6.11) lib/i18n/backend/chain.rb:44:in `catch'
i18n (0.6.11) lib/i18n/backend/chain.rb:44:in `block in translate'
i18n (0.6.11) lib/i18n/backend/chain.rb:43:in `each'
i18n (0.6.11) lib/i18n/backend/chain.rb:43:in `translate'
i18n (0.6.11) lib/i18n/backend/fallbacks.rb:45:in `block (2 levels) in translate'
i18n (0.6.11) lib/i18n/backend/fallbacks.rb:44:in `catch'
i18n (0.6.11) lib/i18n/backend/fallbacks.rb:44:in `block in translate'
i18n (0.6.11) lib/i18n/backend/fallbacks.rb:42:in `each'
i18n (0.6.11) lib/i18n/backend/fallbacks.rb:42:in `translate'
i18n (0.6.11) lib/i18n.rb:157:in `block in translate'
i18n (0.6.11) lib/i18n.rb:153:in `catch'
i18n (0.6.11) lib/i18n.rb:153:in `translate'
actionpack (4.0.12) lib/action_view/helpers/translation_helper.rb:60:in `translate'
app/views/home/index.html.slim:2:in `_app_views_home_index_html_slim__3631594498545859243_70343120045360'
actionpack (4.0.12) lib/action_view/template.rb:143:in `block in render'
activesupport (4.0.12) lib/active_support/notifications.rb:161:in `instrument'
actionpack (4.0.12) lib/action_view/template.rb:141:in `render'
actionpack (4.0.12) lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
actionpack (4.0.12) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.0.12) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.12) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.12) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (4.0.12) lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
actionpack (4.0.12) lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
actionpack (4.0.12) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
actionpack (4.0.12) lib/action_view/renderer/template_renderer.rb:17:in `render'
actionpack (4.0.12) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionpack (4.0.12) lib/action_view/renderer/renderer.rb:23:in `render'
actionpack (4.0.12) lib/abstract_controller/rendering.rb:127:in `_render_template'
actionpack (4.0.12) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionpack (4.0.12) lib/abstract_controller/rendering.rb:120:in `render_to_body'
actionpack (4.0.12) lib/action_controller/metal/rendering.rb:33:in `render_to_body'
actionpack (4.0.12) lib/action_controller/metal/renderers.rb:26:in `render_to_body'
actionpack (4.0.12) lib/abstract_controller/rendering.rb:97:in `render'
actionpack (4.0.12) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.0.12) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
activesupport (4.0.12) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/sfrank/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.0.12) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.0.12) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
actionpack (4.0.12) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.0.12) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.0.12) lib/action_controller/metal/instrumentation.rb:40:in `render'
/Users/sfrank/workspace/soundtaxi/soundtaxi_core/lib/extensions/action_controller/angry_links.rb:31:in `render_with_angry_links'
actionpack (4.0.12) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.0.12) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.0.12) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.12) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.12) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.12) lib/active_support/callbacks.rb:463:in `_run__2236567075907739029__process_action__callbacks'
activesupport (4.0.12) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.12) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.12) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.12) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.12) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.12) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.12) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.12) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.0.12) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.12) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.12) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.12) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.12) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.12) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.0.12) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.12) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.12) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:676:in `call'
/Users/sfrank/workspace/soundtaxi/soundtaxi_core/app/middlewares/soundtaxi_core/flash_session_cookie_middleware.rb:18:in `call'
bullet (4.13.0) lib/bullet/rack.rb:12:in `call'
meta_request (0.3.3) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
rack-contrib (1.1.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.3.3) lib/meta_request/middlewares/headers.rb:16:in `call'
meta_request (0.3.3) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.12) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.12) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.12) lib/active_support/callbacks.rb:373:in `_run__385023784535126988__call__callbacks'
activesupport (4.0.12) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.12) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.12) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.12) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.0.12) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.0.12) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.0.12) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.0.12) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
request_store (1.0.8) lib/request_store/middleware.rb:8:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
dragonfly (0.9.15) lib/dragonfly/middleware.rb:13:in `call'
dragonfly (0.9.15) lib/dragonfly/middleware.rb:13:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.12) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.12) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
dragonfly (0.9.15) lib/dragonfly/middleware.rb:13:in `call'
/Users/sfrank/workspace/soundtaxi/soundtaxi_core/lib/soundtaxi_core/range.rb:38:in `_call'
/Users/sfrank/workspace/soundtaxi/soundtaxi_core/lib/soundtaxi_core/range.rb:34:in `call'
rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
railties (4.0.12) lib/rails/engine.rb:511:in `call'
railties (4.0.12) lib/rails/application.rb:97:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
thin (1.6.2) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.2) lib/thin/connection.rb:84:in `catch'
thin (1.6.2) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.2) lib/thin/connection.rb:53:in `process'
thin (1.6.2) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.6.2) lib/thin/backends/base.rb:73:in `start'
thin (1.6.2) lib/thin/server.rb:162:in `start'
rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
rack (1.5.2) lib/rack/server.rb:264:in `start'
railties (4.0.12) lib/rails/commands/server.rb:84:in `start'
railties (4.0.12) lib/rails/commands.rb:76:in `block in <top (required)>'
railties (4.0.12) lib/rails/commands.rb:71:in `tap'
railties (4.0.12) lib/rails/commands.rb:71:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

**Comment by radar** [comment]
OK, thanks. Can you show me your `Gemfile` and `Gemfile.lock` too?

**Comment by mugwump** [comment]
hi rian, thx for looking into this, but I've solved this in the meantime: A colleague of mine had buried another redis-initialization somewhere deep in a gem: So, although it looked like a rails-store-issue at first glance, it was completely unrelated. 

I guess, we should be more careful how&where ressources like database/redis-connections are acquired, this one was quite nasty...
