### ISSUE TITLE
After security update for rack (2.0.8) redis-store raise errors

### ISSUE THREAD

**Issue by le0pard** [redis-store/redis-store#324]
rack gem release security update 2.0.8 version. Rails also released version 6.0.2.1 with rack >= 2.0.8. After update looks like redis-store stop fully working with mountable endgines, likde sidekiq web interface.

<img width="496" alt="1" src="https://user-images.githubusercontent.com/98444/71152889-58b91f80-2240-11ea-89ac-7429f6c5c279.png">

```
undefined method `match' for #<Rack::Session::SessionId:0x00007fc688381ef8>

redis-store (1.8.1) lib/redis/store/namespace.rb:137:in `interpolate'
redis-store (1.8.1) lib/redis/store/namespace.rb:128:in `namespace'
redis-store (1.8.1) lib/redis/store/namespace.rb:7:in `set'
redis-rack (2.0.6) lib/rack/session/redis.rb:49:in `block (2 levels) in set_session'
connection_pool (2.2.2) lib/connection_pool.rb:65:in `block (2 levels) in with'
connection_pool (2.2.2) lib/connection_pool.rb:64:in `handle_interrupt'
connection_pool (2.2.2) lib/connection_pool.rb:64:in `block in with'
connection_pool (2.2.2) lib/connection_pool.rb:61:in `handle_interrupt'
connection_pool (2.2.2) lib/connection_pool.rb:61:in `with'
redis-rack (2.0.6) lib/redis/rack/connection.rb:20:in `with'
redis-rack (2.0.6) lib/rack/session/redis.rb:79:in `with'
redis-rack (2.0.6) lib/rack/session/redis.rb:49:in `block in set_session'
redis-rack (2.0.6) lib/rack/session/redis.rb:67:in `with_lock'
redis-rack (2.0.6) lib/rack/session/redis.rb:48:in `set_session'
rack (2.0.8) lib/rack/session/abstract/id.rb:498:in `write_session'
rack (2.0.8) lib/rack/session/abstract/id.rb:381:in `commit_session'
rack (2.0.8) lib/rack/session/abstract/id.rb:261:in `context'
rack (2.0.8) lib/rack/session/abstract/id.rb:253:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.2.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.8) lib/rack/method_override.rb:22:in `call'
rack (2.0.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.8) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
rack-utf8_sanitizer (1.6.0) lib/rack/utf8_sanitizer.rb:22:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

session dump:

```
_csrf_token: "UuJuOriJq7BqMzUmWIP/0NnSWa0mlPnNsNzjGw6P2rQ="
csrf: "DHnKOYECorNhL5I/sBuoWyAEhuhtM8Zg+U6J0xVmPao="
just_signed_up: false
session_id: "e6925f4b4dac2f1032e11132c14cb2f75b4a7205b52dd22b59d356f6c3b1bf09"
tracking: {"HTTP_USER_AGENT"=>"8b6bf8f611f4d5ac876d3c09157dfeeb427d4cb0"}
warden.user.user.key: [[1], "$2a$10$QjO/Msy9RtUNOE/ScvP3ae"]
```

In routes:

```
authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
end
```

downgrade to rails 6.0.1 and rack 2.0.7 fixed this issue. Looks like some changes in rack break this gem: https://github.com/rack/rack/compare/2.0.7...2.0.8

P.S. maybe it is issue with redis-rack, I am not sure, which gem need to be fixed for rack update.

**Comment by le0pard** [comment]
Spec which raise this error:

routes.rb

```
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq', as: :sidekiq
  end
```

spec:
```
    context 'admin user' do
      let(:user) { FactoryBot.create(:user, role: 'admin') }

      before do
        login_as(user, scope: user.class.name.underscore.to_sym)
        get sidekiq_path
      end

      subject { response }

      it { is_expected.to be_successful }
      it { is_expected.to have_http_status(:ok) }
    end

```

Gems:

rails (6.0.2.1)
devise (4.7.1)
rspec-rails (4.0.0.beta3)
redis (4.1.3)
redis-actionpack (5.1.0)
redis-rack (2.0.6)
redis-store (1.8.1)
sidekiq (5.2.7)

**Comment by LeandroSNunes** [comment]
Hi @le0pard I'm suffering from a case similar to yours

routes.rb
```
mount Sidekiq::Web => '/queue'
```

when I access sidekiq
![Screen Shot 2019-12-20 at 15 21 25](https://user-images.githubusercontent.com/656458/71281363-7370be80-233c-11ea-9549-1a1e6fffa7b0.png)

```
 excluded from capture: No host specified, no public_key specified, no secret_key specified, no project_id specified

RuntimeError ():

rack (2.0.8) lib/rack/session/abstract/id.rb:31:in `to_s'
redis-store (1.8.1) lib/redis/store/serialization.rb:57:in `encode'
redis-store (1.8.1) lib/redis/store/serialization.rb:5:in `block in set'
redis-store (1.8.1) lib/redis/store/serialization.rb:40:in `_marshal'
redis-store (1.8.1) lib/redis/store/serialization.rb:5:in `set'
redis-store (1.8.1) lib/redis/store/namespace.rb:7:in `block in set'
redis-store (1.8.1) lib/redis/store/namespace.rb:128:in `namespace'
redis-store (1.8.1) lib/redis/store/namespace.rb:7:in `set'
redis-rack (2.1.0.pre) lib/rack/session/redis.rb:49:in `block (2 levels) in write_session'
redis-rack (2.1.0.pre) lib/redis/rack/connection.rb:22:in `with'
redis-rack (2.1.0.pre) lib/rack/session/redis.rb:79:in `with'
redis-rack (2.1.0.pre) lib/rack/session/redis.rb:49:in `block in write_session'
redis-rack (2.1.0.pre) lib/rack/session/redis.rb:67:in `with_lock'
redis-rack (2.1.0.pre) lib/rack/session/redis.rb:48:in `write_session'
rack (2.0.8) lib/rack/session/abstract/id.rb:381:in `commit_session'
rack (2.0.8) lib/rack/session/abstract/id.rb:261:in `context'
rack (2.0.8) lib/rack/session/abstract/id.rb:253:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.6.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.6.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.6.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
lograge (0.10.0) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (5.1.6.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.6.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.6.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.6.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.6.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.8) lib/rack/method_override.rb:22:in `call'
rack (2.0.8) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.8) lib/rack/sendfile.rb:111:in `call'
secure_headers (5.0.5) lib/secure_headers/middleware.rb:13:in `call'
sentry-raven (2.7.3) lib/raven/integrations/rack.rb:51:in `call'
webpacker (4.0.7) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (5.1.6.2) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

Gems
rails (5.2.4.1)
hiredis (0.6.1)
redis (4.1.3)
redis-actionpack (5.1.0)
redis-activesupport (5.2.0)
redis-namespace (1.6.0)
redis-rack (2.1.0.pre)
redis-rails (5.0.2)
redis-store (1.8.1)
rack (2.0.8)
sidekiq (5.2.7)
sidekiq-ent (1.8.1)
sidekiq-pro (4.0.5)

**Comment by le0pard** [comment]
@LeandroSNunes 

Issue solved by https://github.com/redis-store/redis-rack/pull/50 and https://github.com/redis-store/redis-actionpack/pull/28 

@tubbo will decide how to release this changes

**Comment by gingerlime** [comment]
related https://github.com/rack/rack/issues/1432

**Comment by yourtallness** [comment]
Is there any way to get this fix on rails 4.2.11.1 which is limited to rack 1.6.x and consequently also redis-rack prior to 2.1.x?

Thanks in advance

**Comment by eoy** [comment]
Echoing @yourtallness, I'm stuck with the same version.

**Comment by tubbo** [comment]
@yourtallness @eoy it's doable, but not easy enough as "cherry pick the diff from master to v1.5", and I'm working on a bunch of other things right now. PRs will be accepted for security backports, however.
