### ISSUE TITLE
NoMethodError undefined method `match' for Rack::Session

### ISSUE THREAD

**Issue by cpinto** [redis-store/redis-store#340]
Hi, I'm  seeing the above error with the following stacktrace and I haven't been able to understand if it's a version mismatch somewhere. Is there any known incompatibility between rack 2.1.4, redis-rack 2.0.6 and redis-store 1.9.0?

Thanks in advance.

```
redis-store (1.9.0) lib/redis/store/namespace.rb:197:in `interpolate'
redis-store (1.9.0) lib/redis/store/namespace.rb:188:in `namespace'
redis-store (1.9.0) lib/redis/store/namespace.rb:7:in `set'
redis-rack (2.0.6) lib/rack/session/redis.rb:49:in `block (2 levels) in set_session'
redis-rack (2.0.6) lib/redis/rack/connection.rb:22:in `with'
redis-rack (2.0.6) lib/rack/session/redis.rb:79:in `with'
redis-rack (2.0.6) lib/rack/session/redis.rb:49:in `block in set_session'
redis-rack (2.0.6) lib/rack/session/redis.rb:67:in `with_lock'
redis-rack (2.0.6) lib/rack/session/redis.rb:48:in `set_session'
rack (2.1.4) lib/rack/session/abstract/id.rb:508:in `write_session'
rack (2.1.4) lib/rack/session/abstract/id.rb:391:in `commit_session'
rack (2.1.4) lib/rack/session/abstract/id.rb:271:in `context'
rack (2.1.4) lib/rack/session/abstract/id.rb:263:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.4.4) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
rack-contrib (2.1.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.7.2) lib/meta_request/middlewares/headers.rb:16:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.1.4) lib/rack/method_override.rb:24:in `call'
rails_same_site_cookie (0.1.5) lib/rails_same_site_cookie/middleware.rb:13:in `call'
rack (2.1.4) lib/rack/runtime.rb:24:in `call'
activesupport (5.2.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.1.4) lib/rack/sendfile.rb:113:in `call'
actionpack (5.2.4.4) lib/action_dispatch/middleware/ssl.rb:74:in `call'
sentry-raven (2.11.3) lib/raven/integrations/rack.rb:51:in `call'
webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (5.2.4.4) lib/rails/engine.rb:524:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by cpinto** [comment]
After a bit more digging, turns out that disabling sessions for Sidekiq::Web solves the issue. Added the following to routes.rb:

`Sidekiq::Web.set :sessions, false`
