### ISSUE TITLE
'redis cluster' connection raise exception since redis 5.x gem, should support redis-clustering gem.

### ISSUE THREAD

**Issue by sudoudaisuke** [redis-store/redis-store#369]
The 'redis-store' gem depends on the 'redis' gem.
The 'redis' gem since 5.0 does not support redis clusters. redis clusters are supported by the 'redis-clustering' gem.

https://github.com/redis/redis-rb/blob/master/CHANGELOG.md#500

Now I got exception by this code.

```ruby
require 'redis-store'
redis = ::Redis::Store::Factory.create({cluster: 'redis://redis_cluster:7001/0'})
```

exception message

```text
$ bundle exec ruby app.rb
/app/vendor/bundle/ruby/3.2.0/gems/redis-5.0.7/lib/redis.rb:136:in `initialize_client': Redis Cluster support was moved to the `redis-clustering` gem. (RuntimeError)
        from /app/vendor/bundle/ruby/3.2.0/gems/redis-5.0.7/lib/redis.rb:73:in `initialize'
        from /app/vendor/bundle/ruby/3.2.0/gems/redis-store-1.10.0/lib/redis/store.rb:21:in `initialize'
        from /app/vendor/bundle/ruby/3.2.0/gems/redis-store-1.10.0/lib/redis/store/factory.rb:27:in `new'
        from /app/vendor/bundle/ruby/3.2.0/gems/redis-store-1.10.0/lib/redis/store/factory.rb:27:in `create'
        from /app/vendor/bundle/ruby/3.2.0/gems/redis-store-1.10.0/lib/redis/store/factory.rb:10:in `create'
        from app.rb:3:in `<main>'
```

**Comment by slai11** [comment]
Would including `redis-clustering` force the redis-store gem to only support `redis` v5? That said, what is the maintainer's stance on supporting Redis Cluster funtionalities in `redis-store` with the separation of `redis-clustering` from the `redis` gem?

**Comment by rayway30419** [comment]
I will recommend to use native `redis-clustering` with `active_support`
`redis = Redis::Cluster.new(nodes: [])`
`store = ActiveSupport::Cache.lookup_store(:redis_cache_store, { redis: redis })`

**Comment by iain-bryson** [comment]
Same issue here, except for the session. Is it possible to have a `redis-rb` 5 `Redis::Cluster`-based session store?

**Comment by tubbo** [comment]
for anyone reading this, @rayway30419 is correct...you can use the built-in redis cache store with ActiveSupport in modern versions of Rails. it should work with the `redis-clustering` gem inherently.
